#+title: Daily work log of Dheeraj

* Month of May
** [2016-05-16 Mon]
   + What is the task I was assigned today?
   Basics of terminal commands, version control and emacs editors were covered.
   + What did I get done against each task?
   I installed packages with the help of others on the team and then practised using git verion control and emacs editor.

** [2016-05-17 Tue]
   + What is the task I was assigned today?
   Understanding how a web application is built with the help of a schematic diagram and noting important components of the application.
   Understanding how datamodels are created based on client requirements and usage of mathematical operators to represent verbal conditions laid down by the client
   + What did I get done against each task?
   Wrote notes on how a web application is built using emacs editor and put it on my github repository for future reference.
   Revisited sets and relations and applied them while developing datamodels.
   Created a tabular form of all the possible operations the application may need to deal with.
** [2016-05-18 Wed]
   + What is the task I was assigned today?
   Working in teams and writing code in python for implementation of the data model created in the previous session.
   The template was provided and were asked to add and modify the existing file.
   + What did I get done against each task?
   Familiarised myself with object oriented programming and tried to understand the already written code in the file with the help of my teammates. Also tried to understand new code written by the member of the team who had a fair understanding of python.
** [2016-05-19 Thu]
   + What is the task I was assigned today?
   Continue working on implementation of the object model using python and add session class and its operations.
    + What did I get done against each task?
    Wrote code for session class and its corresponding operations. We also added test cases for a few operations, to check if the code was able to do what it was designed to do.
** [2016-05-20 Fri]
   + What is the task I was assigned today?
   Create a new class called System and reorganise operations based on the parts of the state they were actually affecting. Write test cases for all these operations.
   + What did I get done against each task?
   Rewrote code for operations after reorganising them and adding System class. Managed to write test cases for most of the operations and tested them.
   
** Weekly  Summary
   + What are the insights gained?
   Working as a group using version controls like git.
   The manner in which a web application is built, from scratch.
   Using emacs editor for various needs while programming.
   Object oriented programming using Python.
   Building a data model and an object model for an application.
   + What is my footprint in the realization of the project?
   Learnt the basics of building a web application, which is the first step in working towards the completion of the project.
** [2016-05-23 Mon]
   + What is the task I was assigned today?
   Start working on Object relational model, which was the next layer of the application after Object model.
   + What did I get done against each task?
   Understood about the usage of sqlalchemy, flask and other dependencies and installed them on my computer. 
** [2016-05-24 Tue]
   +What is the task I was assigned today?
   Continue working on Object relational model and complete it.
   + What did I get done against each task?
   Finished writing code for the ORM.
** [2016-05-25 Wed]
   + What is the task I was assigned today?
   Complete writing test cases for the ORM and Start working on the Rest API.
   + What did I get done against each task?
   Wrote the test cases and got rid of errors in them. Also learnt about the next layer ie; Rest API.
** [2016-05-26 Thu]
   + What is the task I was assigned today?
   Write code for rest API.
   + What did I get done against each task?
   Wrote code for rest API.
** [2016-05-27 Fri]
   + What is the task I was assigned today?
   Write test cases for rest API and check if it's running alright. Understand about the front-end and the way it will be implemented with respect to our application.
   + What did I get done against each task?
   Wrote test cases for some methods of rest API and tested them. Also, got a brief idea about front-end of the application.
** Weekly  Summary
   + What are the insights gained?
   How the web application is compartmentalised and how the rest API is built.
   + What is my footprint in the realization of the project?
   Understanding the entire process of building a web application could be considered a pre-requisite to working on the project.
** [2016-05-30 Mon]
   + What is the task I was assigned today?
   Get all test cases of rest API running and begin working on the front-end.
   + What did I get done against each task?
   Tried to get rid of the numerous errors that were surfacing while running the test cases for rest API.
** [2016-05-31 Tue]
   + What is the task I was assigned today?
   Start working on the front-end of the application.
   + What did I get done against each task?
   Inspite of trying to fix all the errors of rest API the previous day, some had to be addressed today. Finished writing login logout part of the front-end.
** [2016-06-01 Wed]
   + What is the task I was assigned today?   
   Finish writing the front-end code for the application.
   + What did I get done against each task?
   
   
* Month of June
* Month of July
