#+title: Daily work log of Dheeraj

* Month of May
** [2016-05-16 Mon]
   + What is the task I was assigned today?
   Basics of terminal commands, version control and emacs editors were covered.
   + What did I get done against each task?
   I installed packages with the help of others on the team and then practised using git verion control and emacs editor.

** [2016-05-17 Tue]
   + What is the task I was assigned today?
   Understanding how a web application is built with the help of a schematic diagram and noting important components of the application.
   Understanding how datamodels are created based on client requirements and usage of mathematical operators to represent verbal conditions laid down by the client
   + What did I get done against each task?
   Wrote notes on how a web application is built using emacs editor and put it on my github repository for future reference.
   Revisited sets and relations and applied them while developing datamodels.
   Created a tabular form of all the possible operations the application may need to deal with.
** [2016-05-18 Wed]
   + What is the task I was assigned today?
   Working in teams and writing code in python for implementation of the data model created in the previous session.
   The template was provided and were asked to add and modify the existing file.
   + What did I get done against each task?
   Familiarised myself with object oriented programming and tried to understand the already written code in the file with the help of my teammates. Also tried to understand new code written by the member of the team who had a fair understanding of python.
** [2016-05-19 Thu]
   + What is the task I was assigned today?
   Continue working on implementation of the object model using python and add session class and its operations.
    + What did I get done against each task?
    Wrote code for session class and its corresponding operations. We also added test cases for a few operations, to check if the code was able to do what it was designed to do.
** [2016-05-20 Fri]
   + What is the task I was assigned today?
   Create a new class called System and reorganise operations based on the parts of the state they were actually affecting. Write test cases for all these operations.
   + What did I get done against each task?
   Rewrote code for operations after reorganising them and adding System class. Managed to write test cases for most of the operations and tested them.
   
** Weekly  Summary
   + What are the insights gained?
   Working as a group using version controls like git.
   The manner in which a web application is built, from scratch.
   Using emacs editor for various needs while programming.
   Object oriented programming using Python.
   Building a data model and an object model for an application.
   + What is my footprint in the realization of the project?
   Learnt the basics of building a web application, which is the first step in working towards the completion of the project.
** [2016-05-23 Mon]
   + What is the task I was assigned today?
   Start working on Object relational model, which was the next layer of the application after Object model.
   + What did I get done against each task?
   Understood about the usage of sqlalchemy, flask and other dependencies and installed them on my computer. 
** [2016-05-24 Tue]
   +What is the task I was assigned today?
   Continue working on Object relational model and complete it.
   + What did I get done against each task?
   Finished writing code for the ORM.
** [2016-05-25 Wed]
   + What is the task I was assigned today?
   Complete writing test cases for the ORM and Start working on the Rest API.
   + What did I get done against each task?
   Wrote the test cases and got rid of errors in them. Also learnt about the next layer ie; Rest API.
** [2016-05-26 Thu]
   + What is the task I was assigned today?
   Write code for rest API.
   + What did I get done against each task?
   Wrote code for rest API.
** [2016-05-27 Fri]
   + What is the task I was assigned today?
   Write test cases for rest API and check if it's running alright. Understand about the front-end and the way it will be implemented with respect to our application.
   + What did I get done against each task?
   Wrote test cases for some methods of rest API and tested them. Also, got a brief idea about front-end of the application.
** Weekly  Summary
   + What are the insights gained?
   How the web application is compartmentalised and how the rest API is built.
   + What is my footprint in the realization of the project?
   Understanding the entire process of building a web application could be considered a pre-requisite to working on the project.
** [2016-05-30 Mon]
   + What is the task I was assigned today?
   Get all test cases of rest API running and begin working on the front-end.
   + What did I get done against each task?
   Tried to get rid of the numerous errors that were surfacing while running the test cases for rest API.
** [2016-05-31 Tue]
   + What is the task I was assigned today?
   Start working on the front-end of the application.
   + What did I get done against each task?
   Inspite of trying to fix all the errors of rest API the previous day, some had to be addressed today. Finished writing login logout part of the front-end.
** [2016-06-01 Wed]
   + What is the task I was assigned today?   
   Finish writing the front-end code for the application.
   + What did I get done against each task?
   Wrote front-end code using angular javascript framework.
** [2016-06-02 Thu]
   + What is the task I was assigned today?  
   Deployment of the completed application after testing the application thoroughly. We were expected to deploy the application externally through a server both manually and using ADS(Auto Deployment Services).
   + What did I get done against each task? 
   Completed the application and manually deployed it by creating containers on base 4 virtual machine on the IIITH server. Have a session with Professor Venkatesh and Professor Viswanath and get a brief idea about discrete dynamic systems.
** [2016-06-03 Fri]
   Leave of absence.
** Weekly  Summary
   + What are the insights gained?
   Creating the front-end of an application using angular javascript framework. Creating virtual machines on the IIITH server. Web application development using MVC framework.
   + What is my footprint in the realization of the project?
   Understood a bit of angular javascript and MVC frameworks. These two are of significant importance while working on the project.
** [2016-06-06 Mon]
   + What is the task I was assigned today?  
   Figure out using p5 framework of javascript for animations.
   + What did I get done against each task?
   Read the documentation of p5.js from its website and went through some examples to get a basic idea of using it for animating objects.
** [2016-06-07 Tue]
   + What is the task I was assigned today? 
   Use p5.js to plot the distance vs time graph for given set of initial distance, initial speed and initial accleration.
   + What did I get done against each task?
   Used an iterative loop moving a point pixel by pixel with some time delay to plot the distance vs time graph while also enabling the user to change the values of speed and accleration thereby altering the path all along.
** [2016-06-08 Wed]
   + What is the task I was assigned today? 
   Create more animations using p5 framework of javascript.
   + What did I get done against each task? 
   We brainstormed about different examples that use infinite iterative systems. Started working on a simple game called Atlas.
** [2016-06-09 Thu]
   We completed writing the code for the Atlas game and started working on an example where a ball is randomly thrown among four individuals and the process can be iterated for as many times and one wants.
** [2016-06-10 Fri]
   We completed working on the ball throwing application after getting rid of a persisitent problem in logic.
** Weekly Summary
   We started using p5 framework of javascript, which made it significantly easier to create animations using javascript.
** [2016-06-13 Mon]
   We started working on two new examples viz, traffic signal simulator and an application that takes a polynomial and an x value as input and plots f(x),f(f(x)) and so on.
** [2016-06-14 Tue]
   We continued working on the two applications we started making the previous day and also made minor changes to the ball throwing application.
** [2016-06-15 Wed]
   Finally finished writing the main essential logic code for the three applications. We were asked to make plots to explain the applications in a more elaborate way and started doing it.
** [2016-06-16 Thu]
   Had some issues getting the plots of the traffic signal simulator right but managed to get it done.
** [2016-06-17 Fri]
   We discussed about our applications with the professor and were asked to think about building a framework that can automatically generate animations like our applications upon taking some basic inputs like f and x.
** Weekly Summary
   We familiarised ourselves with p5 framework of javascript and built a couple of applications using them to get a hang of making animations for a lab.
** [2016-06-20 Mon]
   Started using Google Web Designer and checked out fabric.js framework.
** [2016-06-21 Tue]
   
   
   
   
   
   
   
   
* Month of June
* Month of July
