#+title: Daily work log for Dheeraj

* Month of May
** [2016-05-16 Mon]
   + What is the task I was assigned today?
   Basics of terminal commands, version control and emacs editors were covered.
   + What did I get done against each task?
   I installed packages with the help of others on the team and then practised using git verion control and emacs editor.

** [2016-05-17 Tue]
   + What is the task I was assigned today?
   Understanding how a web application is built with the help of a schematic diagram and noting important components of the application.
   Understanding how datamodels are created based on client requirements and usage of mathematical operators to represent verbal conditions laid down by the client
   + What did I get done against each task?
   Wrote notes on how a web application is built using emacs editor and put it on my github repository for future reference.
   Revisited sets and relations and applied them while developing datamodels.
   Created a tabular form of all the possible operations the application may need to deal with.
** [2016-05-18 Wed]
   + What is the task I was assigned today?
   Working in teams and writing code in python for implementation of the data model created in the previous session.
   The template was provided and were asked to add and modify the existing file.
   + What did I get done against each task?
   Familiarised myself with object oriented programming and tried to understand the already written code in the file with the help of my teammates. Also tried to understand new code written by the member of the team who had a fair understanding of python.

** Weekly  Summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?
* Month of June
* Month of July
